# Generated by Django 6.1.1 on 2026-09-14 21:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=150)),
                ('company', models.CharField(db_index=True, max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('tier', models.CharField(choices=[('A', 'Tier A (Quarterly)'), ('B', 'Tier B (Semi-Annual)'), ('C', 'Tier C (Annual)')], default='C', max_length=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('last_validated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['tier', 'status'], name='contacts_co_tier_8564e2_idx'), models.Index(fields=['owner', 'status'], name='contacts_co_owner_i_f61fc2_idx')],
            },
        ),
    ]
